// AUTO-GENERATED — DO NOT EDIT.
// Generated by Dagger TypeScript SDK introspector (cmd/codegen generate-entrypoint).

import { Context, Error as DaggerError, FunctionCachePolicy, TypeDefKind, connection, dag, getRegisteredClass } from "@dagger.io/dagger"
import * as __dagger from "@dagger.io/dagger"
import * as telemetry from "@dagger.io/dagger/telemetry"
import { ZerotrustVolcamp2026 } from "./src/index"

// Load a core/dependency object from its ID via node(id:) and wrap it in the
// matching generated client class. Mirrors the SDK runtime loader; replaces the
// retired load<Type>FromID API (removed in #12041). Some core type names
// collide with JS builtins and get a trailing "_" (e.g. "Module" -> Module_).
function __loadCoreObject(id: string, typeName: string): any {
  const cls =
    (__dagger as any)[typeName] ?? (__dagger as any)[typeName + "_"]
  if (!cls) {
    throw new Error(`generated client class not found for core type: ${typeName}`)
  }
  return new cls(new Context().selectNode(id, typeName))
}

function formatError(e: unknown): DaggerError {
  if (e instanceof Error) {
    let error = dag.error(e.message)
    const ext = (e as { extensions?: Record<string, unknown> }).extensions
    if (ext) {
      for (const [k, v] of Object.entries(ext)) {
        if (v !== "" && v !== undefined && v !== null) {
          error = error.withValue(
            k,
            JSON.stringify(v) as string & { __JSON: never },
          )
        }
      }
    }
    return error
  }
  try {
    return dag.error(JSON.stringify(e))
  } catch {
    return dag.error(String(e))
  }
}

function rebuildZerotrustVolcamp2026(state: any): ZerotrustVolcamp2026 {
  const __obj = Object.assign(Object.create(ZerotrustVolcamp2026.prototype), state ?? {})
  if (state) {
    if (state["source"] !== undefined && state["source"] !== null) {
      __obj["source"] = __loadCoreObject(state["source"], "Directory")
    }
  }
  return __obj
}

async function serializeZerotrustVolcamp2026(__obj: ZerotrustVolcamp2026): Promise<any> {
  if (__obj === null || __obj === undefined) return __obj
  const __state: any = { ...__obj }
  if ((__obj as any)["source"] !== undefined && (__obj as any)["source"] !== null) {
    __state["source"] = await ((__obj as any)["source"]).id()
  }
  return __state
}



async function register(): Promise<string> {
  let mod = dag.module_()
  let obj_ZerotrustVolcamp2026 = dag.typeDef().withObject("ZerotrustVolcamp2026", { sourceMap: dag.sourceMap("src/index.ts", 4, 14) })
  obj_ZerotrustVolcamp2026 = obj_ZerotrustVolcamp2026.withFunction(dag.function_("build", dag.typeDef().withObject("Directory")).withDescription("Build the slide deck. publicPath sets the base path for served assets (e.g. \"/repo-name/\" on GitHub Pages).").withSourceMap(dag.sourceMap("src/index.ts", 15, 3)).withArg("publicPath", dag.typeDef().withKind(TypeDefKind.StringKind), { defaultValue: JSON.stringify("/") as string & { __JSON: never }, sourceMap: dag.sourceMap("src/index.ts", 15, 9) }))
  obj_ZerotrustVolcamp2026 = obj_ZerotrustVolcamp2026.withConstructor(dag.function_("", obj_ZerotrustVolcamp2026).withArg("ws", dag.typeDef().withObject("Workspace"), { sourceMap: dag.sourceMap("src/index.ts", 7, 15) }))
  mod = mod.withObject(obj_ZerotrustVolcamp2026)
  return await mod.id()
}

async function invoke(
  parentName: string,
  fnName: string,
  parentJson: any,
  args: Record<string, any>,
): Promise<any> {
  switch (parentName) {
    case "ZerotrustVolcamp2026": {
      switch (fnName) {

        case "": {
          const __arg_ws = args["ws"] === undefined || args["ws"] === null ? args["ws"] : __loadCoreObject(args["ws"], "Workspace")
          const __result = await new ZerotrustVolcamp2026(__arg_ws) as unknown as ZerotrustVolcamp2026
          return await serializeZerotrustVolcamp2026(__result)
        }

        case "build": {
          const __parent = rebuildZerotrustVolcamp2026(parentJson)
          const __arg_publicPath = args["publicPath"]
          const __result = await __parent.build(__arg_publicPath)
          return await (__result).id()
        }
        default:
          throw new Error(`unknown function ${fnName} on ZerotrustVolcamp2026`)
      }
    }
    default:
      throw new Error(`unknown object ${parentName}`)
  }
}

async function dispatch() {
  await connection(async () => {
    const fnCall = dag.currentFunctionCall()
    const parentName = await fnCall.parentName()

    if (parentName === "") {
      const id = await register()
      await fnCall.returnValue(JSON.stringify(id) as string & { __JSON: never })
      return
    }

    const fnName = await fnCall.name()
    const parentJson = JSON.parse(await fnCall.parent())
    const fnArgs = await fnCall.inputArgs()

    const args: Record<string, any> = {}
    for (const arg of fnArgs) {
      args[await arg.name()] = JSON.parse(await arg.value())
    }

    try {
      const result = await invoke(parentName, fnName, parentJson, args)
      const out = result === undefined || result === null ? "null" : JSON.stringify(result)
      await fnCall.returnValue(out as string & { __JSON: never })
    } catch (e: unknown) {
      await fnCall.returnError(formatError(e))
      process.exit(1)
    }
  }, { LogOutput: process.stdout })
}

dispatch().catch((e) => {
  console.error(e)
  process.exit(2)
})