[modules.typescript-sdk]
source = "dagger.io/sdk/typescript"

[sdks.typescript]
module = "typescript-sdk"

[modules.zerotrust-volcamp-2026]
entrypoint = true
source = ".dagger"

[sdks.typescript.scopes.".dagger"]
is-module = true
name = "zerotrust-volcamp-2026"
